version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network
    container_name: call_dogs_client

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/mydb
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - app-network
    container_name: call_dogs_server

  database:
    image: postgres:15
    container_name: call_dogs_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data: